### PR TITLE
PIP-1319: Update to the latest etcd client

### PR DESCRIPTION
**Pull request by horkhe**
Since the `etcd.Client` package has changed and the client reference is exposed to the world this is an API breaking change, hence version 2 of this module was introduced.

Also:
 * Stubs were re-genrated with the latest protobuf and grpc versions;
 * Deprecated ConsistentHash was removed;
 * HashBytes64 is replaced with HashString64 to avoid unsafe conversions that is reported by `go vet` since v1.16 https://github.com/golang/go/issues/40701#issue-677219527.

### CODE REVIEW

**Comment by thrawn01** [comment]
Since we are currently on pre-release status `Release v1.0.0-rc.9` (Release Candidate 9). I wonder if we should just update the import paths to `/v1` instead of jumping to `/v2`.

**Comment by horkhe** [comment]
@mailgun-ci test this please

**Comment by horkhe** [comment]
@mailgun-ci test this please

**Comment by horkhe** [comment]
I do not think we can get around with adding `v1` to the version path, current top tags are already v1.x.x.

**Pull request merged**
