### PR TITLE
PIP-1490: Improve error logging detail.

### PR DESCRIPTION
**Pull request by Baliedge**
https://mailgun.atlassian.net/browse/PIP-1490

### CODE REVIEW

**Comment by Baliedge** [comment]
retest this please

**Comment by Baliedge** [comment]
retest this please

**Comment by thrawn01** [comment]
Note here that we should squash the commits and remove the PIP-1490, and explain what we did an why in the PR description, as this is a public repo.

**Comment by Baliedge** [comment]
Closed in favor of https://github.com/mailgun/gubernator/pull/120.

**Pull request closed without merging**
