### PR TITLE
Helm Chart design proposal

### PR DESCRIPTION
**Pull request by matheus-meneses**
Hello Guys, 

I built this helm chart to make the gubernator deploy in kubernetes easier, it's a draft PR yet.

I have to write all documentation, but before, i want to discuss if all specs is according with gubernator.

Here is an example how spec will be rendered

```yaml
---
# Source: helm/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asdf
  labels:
    
    app: gubernator
    helm.sh/chart: helm-1.0.0
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: asdf
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: asdf
    meta.helm.sh/release-namespace: mag
---
# Source: helm/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: asdf
  labels:
    
    app: gubernator
    helm.sh/chart: helm-1.0.0
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: asdf
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: asdf
    meta.helm.sh/release-namespace: mag
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - watch
---
# Source: helm/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: asdf
  labels:
    
    app: gubernator
    helm.sh/chart: helm-1.0.0
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: asdf
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: asdf
    meta.helm.sh/release-namespace: mag
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: asdf
subjects:
  - kind: ServiceAccount
    name: asdf
---
# Source: helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: asdf
  labels:
    
    app: gubernator
    helm.sh/chart: helm-1.0.0
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: asdf
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: asdf
    meta.helm.sh/release-namespace: mag
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 81
      targetPort: 81
      protocol: TCP
      name: grpc
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: asdf
---
# Source: helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gubernator
  labels:
    
    app: gubernator
    helm.sh/chart: helm-1.0.0
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: asdf
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: asdf
    meta.helm.sh/release-namespace: mag
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: helm
      app.kubernetes.io/instance: asdf
  template:
    metadata:
      labels:
        
        app: gubernator
        helm.sh/chart: helm-1.0.0
        app.kubernetes.io/name: helm
        app.kubernetes.io/instance: asdf
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: asdf
      
      containers:
        - name: gubernator
          env:
          
          - name: GUBER_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GUBER_K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: GUBER_GRPC_ADDRESS
            value: "0.0.0.0:81"
          - name: GUBER_HTTP_ADDRESS
            value: "0.0.0.0:80"
          - name: GUBER_PEER_DISCOVERY_TYPE
            value: "k8s"
          - name: GUBER_K8S_POD_PORT
            value: 81
          - name: GUBER_K8S_ENDPOINTS_SELECTOR
            value: "app=gubernator"
          - name: GUBER_K8S_WATCH_MECHANISM
            value: "endpoints"
          image: thrawn01/gubernator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 81
            - name: http
              containerPort: 80
          livenessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 81
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 20
            tcpSocket:
              port: 81
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
      nodeSelector:
        group: apps

```

Default values

```yaml
gubernator:

  fullnameOverride: {}
  nameOverride: {}
  priorityClassName: {}

  autoscaling:
    enabled: false

  replicaCount: 4

  image:
    repository: thrawn01/gubernator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

#  labels:
#    a: "b"

#  debug: true
#  watchPods: true

  server:
    http:
      port: "80"
    grpc:
      port: "81"
#      maxConnAgeSeconds: 30

  annotations: { }

  serviceAccount:
    create: true
#    name: "teste"

  nodeSelector:
    group: apps

  resources:
    requests:
      cpu: 100m
      memory: 150Mi
```
I hope you enjoy and thanks for the awesome project.

### CODE REVIEW

**Comment by thrawn01** [comment]
This looks great! We not very familiar with helm or k8s as we don't use it internally and I've only played with it. So we rely on the community to do the right thing for k8s users. If you build it and test it I'll make sure it gets merged.

**Comment by thrawn01** [comment]
Would you be willing to put something in the readme on how to build the helm? Alternatively could you add a `build-helm` target in the make file? This would assist those who are not overly familiar with helm.

**Comment by matheus-meneses** [comment]
Hello @thrawn01, of course. I'll do some fixes and build a full documentation.

Thanks for your time.

**Review by thrawn01 — APPROVED** [review]
This one has been sitting out here for a while, still needs some documentation for those of us who don't know much about helm, but I imagine this should be useful to someone else who knows what they are doing, so I'll go ahead and merge it.

**Comment by matheus-meneses** [comment]
Hi thrawn, i'm sorry about the late, i have made some tunnings in helm chart, later i'll open a PR with docs e how to deploy using helmchart

**Pull request merged**
