### PR TITLE
Update Go to 1.17.11

### PR DESCRIPTION
**Pull request by pzduniak**
Once again, for the sake of satisfying security vuln scanners.

### CODE REVIEW

**Comment by pzduniak** [comment]
@Baliedge Per https://github.com/mailgun/gubernator/pull/140#issue-1218971965:

>That way updates that address Go CVEs will be more intentional, rather than just a rebuild of the latest release.

I think it's better if you approve my PRs and merge them (I can keep making them - it's a part of my role), rather than responding to my requests (in the form of issues) to rerelease HEAD without changes. Hopefully you don't mind it - I'm open to suggestions if you have any other ideas.

**Comment by Baliedge** [comment]
@pzduniak I'm trying to understand your environment.  Does it not have the ability rebuild and pull latest images?  Do you mind elaborating on the build environment you use?

**Comment by pzduniak** [comment]
@Baliedge Rather than rebuilding images from scratch, we review the published GHCR ones, approve and cache them through a proxy. I think that the official published images should always be up to date vulndb-wise _and_ explicit Go updates are better than rebuilding the images w/o source code changes on request.

**Comment by Baliedge** [comment]
@pzduniak Understood.  We will approve any patch updates you provide.

**Pull request merged**
